### ISSUE TITLE
dependency hardcoded to be conan 1.41.0 causes troubles in newer projects

### ISSUE THREAD

**Issue by volviq** [CycloneDX/cyclonedx-conan#44]
https://github.com/CycloneDX/cyclonedx-conan/blob/main/pyproject.toml 
Specifies:
conan = "1.41.0"
Instead a range seems to be valid as well.
cyclonedx conan works fine locally with conan 1.49.0. 1.49.x brings several improvements which are required by our project.

So specifying:
pendulum = "^1.41.0" 
Should be sufficient to permit all versions up to 1.49.9
See https://python-poetry.org/docs/dependency-specification/ for format specification.

**Comment by jkowalleck** [comment]
closed via #45
