### ISSUE TITLE
BOM not usable from stdout directly

### ISSUE THREAD

**Issue by codetent** [CycloneDX/cyclonedx-conan#52]
Executing the tool and then extracting the BOM from stdout does not work if conan outputs logging information to stdout too. Then the two outputs are mixed and piping stdout to a file does not work.

I guess this happens because conan is configured with default settings and conan info is used (https://github.com/CycloneDX/cyclonedx-conan/blob/main/src/command.py#L81). If e.g., recipes are missing, conan automatically fetches them and prints messages to stdout.

Personally, I would prefer if there is a parameter to specify an output file for the generated json. Otherwise, the conan output could also be suppressed but this could make debugging harder.

**Comment by jkowalleck** [comment]
preferred solution: logs go to stdError.

**Comment by jkowalleck** [comment]
closed via #83
