### ISSUE TITLE
Exclude development dependencies

### ISSUE THREAD

**Issue by andreas-hilti** [CycloneDX/cyclonedx-conan#85]
I would like to have an option to exclude development dependencies (for instance build tools).

Consider for instance the following conanfile.txt:
```
[tool_requires]
cmake/3.26.3
[requires]
openssl/1.1.1t
```
If I now install the dependencies:
`conan install conanfile.txt -s compiler.runtime=MD -s compiler="Visual Studio" -s compiler.version=16`
and then generate the SBOM:
`cyclonedx-conan -l conan.lock conanfile.txt`
this then lists
`"bom-ref": "pkg:conan/cmake@3.26.3?repository_url=https://center.conan.io"`
as well as
`"bom-ref": "pkg:conan/openssl@1.1.1t?repository_url=https://center.conan.io"`
in the generated SBOM.

Instead, I would like to have an option, say `--exclude-dev`
`cyclonedx-conan -l conan.lock conanfile.txt --exclude-dev`
which then lists only 
`"bom-ref": "pkg:conan/openssl@1.1.1t?repository_url=https://center.conan.io"`
in the generated SBOM.

**Comment by jkowalleck** [comment]
closed via #86
